---
abstract: 'OO access to the MealMaster recipe files'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  Text::Diff: 1.37
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-MealMaster
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  File::MealMaster:
    file: lib/File/MealMaster.pm
    version: v0.17.8
  File::MealMaster::Result:
    file: lib/File/MealMaster/Result.pm
    version: v0.17.6
  File::MealMaster::Storage:
    file: lib/File/MealMaster/Storage.pm
    version: v0.17.6
recommends:
  App::cpanminus: 1.6005
requires:
  Class::Method::ModifiersX::Augment: 0.001
  File::DataClass: v0.22.0
  MealMaster: 0.28
  Moo: 1.002
  Template: 2.22
  namespace::clean: 0.23
  namespace::sweep: 0.006
  parent: 0.224
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-MealMaster
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.17.8
